// <auto-generated />
namespace LabG9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Lab_g9_31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lab_g9_31));
        
        string IMigrationMetadata.Id
        {
            get { return "202411142117383_Lab_g9_31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
