// <auto-generated />
namespace LabG9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class lab9_g2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lab9_g2));
        
        string IMigrationMetadata.Id
        {
            get { return "202411140344444_lab9_g2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
